FROM python:3.12-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /home/spherre_backend/src

COPY backend .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

RUN chmod +x ./start

CMD ["./start"]