#!/bin/bash
set -e

# Ensure we're in the correct directory
cd "$(dirname "$0")"

# Check if virtual environment is activated
if [[ -z "$VIRTUAL_ENV" ]]; then
    echo "Warning: No virtual environment detected. Consider activating one."
fi


python -m spherre.wsgi