export const routes = (address: `0x${string}` | null) => ({
  dashboard: `/account/${address}/`,
  depositViaAddress: `/account/${address}/deposit/deposit-via-address`,
  depositViaWallet: `/account/${address}/deposit/deposit-via-wallet`,
  trade: `/account/${address}/trade`,
  members: `/account/${address}/members`,
  transactions: `/account/${address}/transactions`,
  transactionDetails: (id: string) => `/account/${address}/transactions/${id}`,
  stake: `/account/${address}/stake`,
  smartWill: `/account/${address}/smart-will`,
  treasury: `/account/${address}/treasury`,
  smartLock: `/account/${address}/smart`,
  payments: `/account/${address}/payments`,
  apps: `/account/${address}/apps`,
  settings: `/account/${address}/settings`,
  editProfile: `/account/${address}/settings/edit-profile`,
  support: `/account/${address}/support`,
})
